import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Arjun Prajapati Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <div className="bg-black min-h-screen ">
          {children}
        </div>
      </body>
    </html>
  );
}
